name: postgresql_services

on: [push]

jobs:
  postgresql:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: show locale
        run: docker run --rm postgres:11.5 psql -h localhost  -U postgres -c "SHOW LC_COLLATE;"
